currencies = {
    "USD": "United States Dollar",
    "EUR": "Euro",
    "JPY": "Japanese Yen",
    "BGN": "Bulgarian Lev",
    "CZK": "Czech Koruna",
    "DKK": "Danish Krone",
    "GBP": "British Pound Sterling",
    "HUF": "Hungarian Forint",
    "PLN": "Polish Zloty",
    "RON": "Romanian Leu",
    "SEK": "Swedish Krona",
    "CHF": "Swiss Franc",
    "ISK": "Icelandic Krona",
    "NOK": "Norwegian Krone",
    "HRK": "Croatian Kuna",
    "RUB": "Russian Ruble",
    "TRY": "Turkish Lira",
    "AUD": "Australian Dollar",
    "BRL": "Brazilian Real",
    "CAD": "Canadian Dollar",
    "CNY": "Chinese Yuan",
    "HKD": "Hong Kong Dollar",
    "IDR": "Indonesian Rupiah",
    "ILS": "Israeli New Shekel",
    "INR": "Indian Rupee",
    "KRW": "South Korean Won",
    "MXN": "Mexican Peso",
    "MYR": "Malaysian Ringgit",
    "NZD": "New Zealand Dollar",
    "PHP": "Philippine Peso",
    "SGD": "Singapore Dollar",
    "THB": "Thai Baht",
    "ZAR": "South African Rand"
}

countrycodeconversion = {
    "USD": "US",
    "EUR": "EU",
    "JPY": "JP",
    "BGN": "BG",
    "CZK": "CZ",
    "DKK": "DK",
    "GBP": "GB",
    "HUF": "HU",
    "PLN": "PL",
    "RON": "RO",
    "SEK": "SE",
    "CHF": "CH",
    "ISK": "IS",
    "NOK": "NO",
    "HRK": "HR",
    "RUB": "RU",
    "TRY": "TR",
    "AUD": "AU",
    "BRL": "BR",
    "CAD": "CA",
    "CNY": "CN",
    "HKD": "HK",
    "IDR": "ID",
    "ILS": "IL",
    "INR": "IN",
    "KRW": "KR",
    "MXN": "MX",
    "MYR": "MY",
    "NZD": "NZ",
    "PHP": "PH",
    "SGD": "SG",
    "THB": "TH",
    "ZAR": "ZA"
}